### ISSUE TITLE
dependency error, load error

### ISSUE THREAD

**Issue by mstram** [eisental/LibraryTemplate#1]
1) The maven build fails, evidently because of the old version or typo ? in the pom.xlm file :

<dependency>
            <groupId>org.bukkit</groupId>
            <artifactId>bukkit</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

2) After changing the above to 
            <version>1.0.0-R1-SNAPSHOT</version>

it builds, but then gets a load error (using craftbukkit-1.0.1-R1.jar) :

java.lang.ClassCastException: class org.tal.librarytemplate.Mike1
        at java.lang.Class.asSubclass(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:171)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:215)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:136)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:151)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:127)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigur
ationManager.java:52)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:145)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:399)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

Mike

**Comment by eisental** [comment]
Thanks. It should work now. There's probably a problem with your code, though. Maybe your plugin class doesn't extends JavaPlugin?

**Comment by mstram** [comment]
> Maybe your plugin class doesn't extends JavaPlugin?

I was just using the sample 'test' class (shouldn't it have been named Test (uppercase), which I renamed to Mike1, but didn't change anything in it.

I thought that test code was "ready to (compile / run)" ?

I did find something about JavaPlugin on a quick search for Bukkit plugins, but when I changed the code from 

public class Mike1 extends Circuit {

// public class Mike1 extends JavaPlugin {

... that led to a plethora of compile errors.

I tried a quick fix by just adding import statements for everything "bukkit", but that didn't work.

I will try your updated version and let you know

But  I AM able to compile the main RedstoneChips project, and run it, so I'll get back to the lib-template, after I get somewhat up to speed on the main code.

MIke

**Comment by mstram** [comment]
Thx, I addded comments on github

On another note, I found this very nice free 68000 simulator / editor
/ assembler.

http://www.easy68k.com/easy68kexamples.htm

I have an Atari 1040 in very good condition, working... so a 68000
chip might be my next project :)

And then after that ..
http://www.hercules-390.org/

I've played around with Hercules quite, a bit, but it's strictly text
based (old IBM emulation).

So a 370 chip next with RSGC :)

On 12/21/11, Tal Eisenberg
reply@reply.github.com
wrote:
